name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  debug:
    name: Debug Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Event Payload
        run: |
          echo "Event payload:"
          echo "${{ toJson(github.event) }}"

      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
