name: Folder-specific Workflows

on:
  push:
    branches:
    - main

jobs:
  folder_abc:
    name: ABC Folder Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Check for changes in abc folder
      id: changes
      run: |
        files=()
        for file in "${{ github.event.head_commit.modified }}"; do
          if [[ $file == abc/** ]]; then
            files+=("$file")
          fi
        done
        if [ ${#files[@]} -gt 0 ]; then
          echo "::set-output name=result::true"
        else
          echo "::set-output name=result::false"
        fi

    - name: Run if changes in abc folder
      if: steps.changes.outputs.result == 'true'
      run: |
        echo "Modified files:"
        echo "${{ github.event.head_commit.modified }}"
        ls abc

  folder_123:
    name: 123 Folder Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Check for changes in 123 folder
      id: changes
      run: |
        files=()
        for file in "${{ github.event.head_commit.modified }}"; do
          if [[ $file == 123/** ]]; then
            files+=("$file")
          fi
        done
        if [ ${#files[@]} -gt 0 ]; then
          echo "::set-output name=result::true"
        else
          echo "::set-output name=result::false"
        fi

    - name: Run if changes in 123 folder
      if: steps.changes.outputs.result == 'true'
      run: |
        echo "Modified files:"
        echo "${{ github.event.head_commit.modified }}"
        ls 123
