name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  folder_abc:
    name: ABC Folder Workflow
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.modified, 'abc/') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in abc folder
        run: |
          tree abc

  folder_123:
    name: 123 Folder Workflow
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.modified, '123/') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in 123 folder
        run: |
          ls 123
