name: Folder-specific Workflows

on:
  push:
    branches:
    - main

jobs:
  folder-specific:
    name: Folder-specific Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Check for changes
      id: changes
      run: |
        abc_modified=false
        one23_modified=false
        for file in "$(cat $GITHUB_EVENT_PATH | jq -r '.head_commit.modified[]')"; do
          if [[ $file == abc/* ]]; then
            abc_modified=true
          fi
          if [[ $file == 123/* ]]; then
            one23_modified=true
          fi
        done
        if $abc_modified; then
          echo "::set-output name=folder::abc"
        elif $one23_modified; then
          echo "::set-output name=folder::123"
        else
          echo "::set-output name=folder::none"
        fi
      shell: bash

    - name: Run if changes in abc folder
      if: steps.changes.outputs.folder == 'abc'
      run: |
        echo "Modified files:"
        cat $GITHUB_EVENT_PATH | jq -r '.head_commit.modified[]'
        ls abc

    - name: Run if changes in 123 folder
      if: steps.changes.outputs.folder == '123'
      run: |
        echo "Modified files:"
        cat $GITHUB_EVENT_PATH | jq -r '.head_commit.modified[]'
        ls 123
