name: Folder-specific Workflows

on:
  push:
    branches:
    - main

jobs:
  folder_abc:
    name: ABC Folder Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.commits | length > 0 && github.event.commits[0].modified | contains('abc/**') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Debug Modified Files
      run: |
        echo "Modified files:"
        echo "${{ github.event.commits[0].modified }}"

    - name: List files in abc directory
      run: |
        ls abc

  one:
    name: 123 Folder Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.commits | length > 0 && github.event.commits[0].modified | contains('123/**') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Debug Modified Files
      run: |
        echo "Modified files:"
        echo "${{ github.event.commits[0].modified }}"

    - name: List files in 123 directory
      run: |
        ls 123
